version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hot_password
      POSTGRES_USER: hot_user
      POSTGRES_DB: hot_db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db