# Generated by Django 2.2.3 on 2020-01-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200105_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_pic',
            field=models.ImageField(default='backendrestaurantes/static/img/ajidegallina.jpg', upload_to=''),
        ),
    ]
