# Generated by Django 2.2.3 on 2020-01-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_food_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='food_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='food_orders', to='api.FoodTable'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Sale'),
        ),
    ]
