# Generated by Django 2.2.3 on 2020-01-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200107_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_pic',
            field=models.ImageField(default='/static/img/ajidegallina.jpg', upload_to=''),
        ),
    ]
