# Generated by Django 2.2.3 on 2020-01-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200107_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.OrderStatus'),
        ),
    ]
