# Generated by Django 2.2.9 on 2020-01-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200128_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
