# Generated by Django 2.2.10 on 2020-03-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200312_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='food_orders', to='api.Sale'),
        ),
    ]
