# Generated by Django 2.2.10 on 2020-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200323_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
